### PR TITLE
[FIX] grab missing shows

### PR DESCRIPTION
**Pull request by thomich**
hey all

i tried to fix grabbing missing shows for tv_grab_ch_search and i had success.
as i'm not a pure perl developer, please review my code and comment, ask, change if needed...

thanks a lot

regards
thomi

### CODE REVIEW

**Comment by bhaak** [comment]
I wasn't aware of any missing shows. What kind of shows are missing? When does it happen?

**Comment by thomich** [comment]
like shows in prime time... it skipped lot of shows.. after my change i was able to get a lot of more shows and now show is missing.. i deeply checked with tv.search.ch tv listing and compared...

tv_grab_ch_search_before

tv_grab_ch_search_after

**Comment by bhaak** [comment]
Running the current version and your version side by side, I see the missing shows as well.
Strange that I didn't notice that before (I use MythTV as well).
I'll have to verify that your fix does the right thing (like generate no duplicates, etc.) but thanks for pointing me in the right direction.

**Comment by thomich** [comment]
hey.. you're welcome and thanks for review my code ;)
hope you can maybe beautify it ;)

**Comment by bhaak** [comment]
Fixed with 8d07e82. The datetime object used to filter the programmes (so there are no duplicates as we need to stitch together a day by pages which only have 4 hours) didn't have the minutes and seconds set to zero (d'oh) and the wrong timezone didn't help either.

I've been running a test with the new code since yesterday and so far, it looks good.

**Comment by thomich** [comment]
have applied your code and will test it..

many thanks

**Comment by thomich** [comment]
hey @bhaak 

it works perfect... thanks a lot for fixing it..

regards from ch
thomi

**Pull request closed without merging**
